### ISSUE TITLE
Any Plan to Support Animated GIF Files?

### ISSUE THREAD

**Issue by vus7294** [kometen/http_post#2]
I asked you to support multiple files convert. and it works. half perfect.
next is...
I have some Animated GIFs. but I convert normally and view some tools, it isn't animated. freeze at first scene.
Hey. I have another request. animated GIF. is it sweet for convert? thanks for read this.

**Comment by kometen** [comment]
Hi. Thank you for getting in touch again. I will be looking into how to make animations. It sounds like a good idea. I am not sure when I can begin looking at it, but I will give it a try.

Best regards
Claus

**Comment by vus7294** [comment]
good news. I can sync or put heif to iPhone now.
so I can see heif files on iPhone right now.
it needs iTunes 12.7(newest).
but no sequence heif right now! i hope to make sequence heif files from gif files!

**Comment by kometen** [comment]
That is nice. Thank you for testing this tool. You can share it with your friends if you want to.

Regards
Claus
